# This is going to be a scheduled trade routine.
name: Trade Routine

on:
  schedule:
    - cron: "0 14 * * 1-5"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Find cached env
      id: find-venv
      uses: actions/cache@v2
      with:
        path: env
        key: venv-trade-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          venv-build-
          
    - name: Create env
      id: create-venv
      if: steps.find-venv.outputs.cache-hit != 'true'
      run: |
        python -m venv env
        source env/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt

    - name: Ensure dependencies
      run: |
        source env/bin/activate
        python -m pip install --upgrade -r requirements.txt

    - name: Run routine
      env:
          MFA_KEY: ${{ secrets.MFA_KEY }}
          RH_USERNAME: ${{ secrets.RH_U }}
          RH_PASSWORD: ${{ secrets.RH_V }}
          TG_CHAT_ID: ${{ secrets.TG_C }}
          TG_BOT_TOKEN: ${{ secrets.TG_T }}
      run: |
        # configure git
        git config --global user.name 'Minibot'
        git config --global user.email 'minibot@tr4d3r.com'
        # activate venv
        source env/bin/activate
        # the actual trading workflow
        python routine.py minibot
        git add **/folio.json.*
        # a dummy to test other functionalities
        python dummy.py
        git add dummy_data/
        # commit and push
        git commit -m "Automated trade"
        git push

